name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -e .[dev]
      - name: Run unit tests
        run: |
          . .venv/bin/activate
          pytest -q

  browsers:
    name: Prepare Playwright browsers (cache)
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Restore Playwright cache
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
            ~/.cache/playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-
      - name: Install dependencies and Playwright
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -e .[dev]
          # Always run install here to populate cache if missing
          playwright install --with-deps
      - name: Get Playwright version
        id: playwright-version
        run: |
          . .venv/bin/activate
          VERSION=$(python -c "import importlib.metadata as m; print(m.version('playwright'))") || VERSION=unknown
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Save Playwright cache (versioned)
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
            ~/.cache/playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

  behave:
    name: Behave (Playwright)
    needs: [unit, browsers]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Restore Playwright cache
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
            ~/.cache/playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-
      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -e .[dev]
      - name: Install Playwright browsers (if cache miss)
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: |
          . .venv/bin/activate
          playwright install --with-deps
      - name: Run Behave features
        run: |
          . .venv/bin/activate
          behave -f pretty
