name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install deps and run tests (skip local)
        run: |
          python -m venv .venv
          ./.venv/bin/python -m pip install -e '.[dev]'
          set -o pipefail
          ./.venv/bin/python -m pytest -q -m "not local"

  smoke:
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Quick smoke check
        run: |
          python - <<'PY'
          import sys
          try:
              # simple import and minor check to ensure env is sane
              import pytest
              print('smoke ok')
              sys.exit(0)
          except Exception as e:
              print('smoke failed:', e)
              sys.exit(2)
          PY

