name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install deps and run tests (skip local)
        run: |
          python -m venv .venv
          ./.venv/bin/python -m pip install -e '.[dev]'
          set -o pipefail
          ./.venv/bin/python -m pytest -q -m "not local"



